### PR TITLE
More additions

### PR DESCRIPTION
**Pull request by TomWright**
Created path constants so it is easier to access certain parts of the file system.
Implemented the CommandBus pattern.

### CODE REVIEW

**Comment by JordanDoyle** [comment]
Appreciate all the work you're doing fof Animus, thanks mate. I'll look over your PR later today when I'm on my PC

**Comment by TomWright** [comment]
No problem! Give's me something to do outside of work ^^

**Comment by JordanDoyle** [comment]
Before merging this in I'm going to have to make some sort of conventions for stuff like this I think. I'll leave the PR open but it might need some edits such as `Commanding` becoming `Command` and `UserWasCreated` to `UserCreated` and `EventListenerInterface` becoming a trait, however I do really like the additions. I'll write up a some initial conventions then ask for some contributions/changes to them.

**Comment by TomWright** [comment]
I thinking Commanding => Command and Eventing => Event makes sense.
I think that the event names however are more of an application specific thing rather than for definition within the framework. I've only included those files in my commits so as you know roughly how they would be used.
Let me know what changes to make.

**Comment by TomWright** [comment]
May I suggest PSR-1/2 standards? PHP Storm comes with a nice preset for these. I use these standards at work so I do most of them automatically anyway

**Comment by JordanDoyle** [comment]
That's exactly what I was thinking, here's the standards so far:

7b0a3e5e64 1

**Comment by TomWright** [comment]
Looking good. Is there any reason why you want to use tabs over spaces?

**Comment by JordanDoyle** [comment]
I guess it's down to preference. It's also easy to change the tab-size in IDEs.

**Comment by TomWright** [comment]
There you go :)

**Comment by JordanDoyle** [comment]
Is this all tested and working? Did you manage to get the routes working? also, don't forget the event stuff 😊

**Comment by TomWright** [comment]
I've done the same for Events now.
I tested it using the following:

echo '<pre>';
var_dump('start');
$bus = \Animus\Command\CommandBus::get();
$command = new \App\Command\Commands\CreateUserCommand('Tom', 'Wright', 'contact@tomwright.me');
$bus->execute($command);
var_dump('end');
die;

I haven't got routes working yet so I just testing it inside your getTestFunction in the TestController.

**Pull request merged**
